const EVENT_TYPES = {
  LESSON: 'EVENT_TYPES.LESSON',
  PRACTICE: 'EVENT_TYPES.PRACTICE',
  MASTERCLASS: 'EVENT_TYPES.MASTERCLASS',
  CONCERT: 'EVENT_TYPES.CONCERT',
  OPERA: 'EVENT_TYPES.OPERA',
  RECITAL: 'EVENT_TYPES.RECITAL',
  OTHER: 'EVENT_TYPES.OTHER',
}

module.exports = {
  EVENT_TYPES,
}
